name: Sync fork with upstream
on:
  schedule:
    - cron: '0 6 * * *'   # diario 06:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream & fetch
        run: |
          git remote add upstream https://github.com/shahnami/sara.git
          git fetch upstream

      - name: Merge upstream/main -> main
        run: |
          git checkout main
          git merge --ff-only upstream/main || git merge --no-edit upstream/main
          git push origin main
